apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: d64364ca-4205-4fd7-90c4-a86da9299c01
      accessKey:
        secretRef:
          name: scaleway-eso-credentials
          namespace: external-secrets
          key: ESO_ACCESS_KEY
      secretKey:
        secretRef:
          name: scaleway-eso-credentials
          namespace: external-secrets
          key: ESO_SECRET_KEY
