apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-controller
  interval: 5m
  path: "./infrastructure/cert-manager/config/kustomize/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
