apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator-controller
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/external-secrets-operator/controller/kustomize/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
