apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-secrets-operator-controller-flux-kustomization.yaml
- external-secrets-operator-config-flux-kustomization.yaml
- gitlab-runner-controller-flux-kustomization.yaml
- kube-prometheus-stack-flux-kustomization.yaml
- istio-controller-flux-kustomization.yaml
- istio-config-flux-kustomization.yaml
- external-dns-controller-flux-kustomization.yaml
