apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-values
spec:
  dataFrom:
  - extract:
      key: name:gitlab-runner-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: gitlab-runner-values
    template:
      data:
        values.yaml: |
          runnerToken: {{ .runnerToken }}
