apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - conf/values.yaml
  name: kube-prometheus-stack-values
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: monitoring
resources:
- manifests
