alertmanager:
  alertmanagerSpec:
   externalUrl: https://alertmanager.dev.private.aliktb.com
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'discord'
      routes:
      - matchers:
        - alertname = "InfoInhibitor"
        receiver: 'null'
      - matchers:
        - alertname = "Watchdog"
        receiver: 'null'
    receivers:
    - name: 'discord'
      slack_configs:
      - channel: '#dev-alerts'
        send_resolved: true
        title: 'Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Severity:* {{ .Labels.severity }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
    - name: 'null'
  enabled: true
  route:
    main:
      annotations:
        external-dns/enabled: "true"
      apiVersion: gateway.networking.k8s.io/v1
      enabled: true
      hostnames:
      - alertmanager.dev.private.aliktb.com
      kind: HTTPRoute
      parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: internal-private-gateway
        namespace: istio-internal-private
        sectionName: https
grafana:
  enabled: true
  route:
    main:
      annotations:
        external-dns/enabled: "true"
      apiVersion: gateway.networking.k8s.io/v1
      enabled: true
      hostnames:
      - grafana.dev.private.aliktb.com
      kind: HTTPRoute
      parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: internal-private-gateway
        namespace: istio-internal-private
        sectionName: https
  ## Configure additional grafana datasources (passed through tpl)
  ## ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
  additionalDataSources:
  - access: proxy
    basicAuth: false
    editable: false
    isDefault: false
    name: Loki
    orgId: 1
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local
    version: 1
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  enabled: true
  prometheusSpec:
    # Allow discovery of PodMonitors in ALL namespaces
    podMonitorNamespaceSelector: {}
    # Allow discovery of ServiceMonitors in ALL namespaces
    serviceMonitorNamespaceSelector: {}
  route:
    main:
      annotations:
        external-dns/enabled: "true"
      apiVersion: gateway.networking.k8s.io/v1
      enabled: true
      hostnames:
      - prometheus.dev.private.aliktb.com
      kind: HTTPRoute
      parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: internal-private-gateway
        namespace: istio-internal-private
        sectionName: https
