alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'discord'
      routes:
      - matchers:
        - alertname = "InfoInhibitor"
        receiver: 'null'
      - matchers:
        - alertname = "Watchdog"
        receiver: 'null'
    receivers:
    - name: 'discord'
      slack_configs:
      - channel: '#dev-alerts'
        send_resolved: true
        title: 'Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Severity:* {{ .Labels.severity }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
    - name: 'null'
  enabled: true
  ingress:
    enabled: true
    ingressClassName: tailscale
    tls:
    - hosts:
      - alertmanager
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: tailscale
    tls:
    - hosts:
      - grafana
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
