apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - service=conf/gateway-service-config.yaml
  name: gateway-config
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: istio-internal
resources:
- manifests
