apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scaleway-dns-api-keys
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  dataFrom:
  - extract:
      key: name:scaleway-dns-api-keys
      version: latest_enabled
