apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - conf/values.yaml
  name: gitlab-runner-values
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: gitlab
resources:
- manifests
