apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
spec:
  data:
  - secretKey: discord-webhook-url
    remoteRef:
      key: name:alertmanager-discord-webhook
      property: DISCORD_WEBHOOK_URL
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: alertmanager-discord-webhook
    creationPolicy: Owner
